# Generated by Django 4.2.2 on 2023-07-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='url',
            field=models.CharField(default='blog_index', max_length=111),
        ),
    ]
