# Generated by Django 4.2.2 on 2023-07-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_englishrules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='englishwords',
            name='rules',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
