# Generated by Django 4.2.2 on 2023-07-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_alter_englishwords_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='englishwords',
            name='rules',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
