# Generated by Django 4.2.2 on 2023-07-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_alter_englishwords_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='englishwords',
            name='word',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
