# Generated by Django 4.2.2 on 2023-07-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0009_alter_englishwords_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='PythonQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField(null='True')),
                ('need', models.BooleanField(default='False')),
            ],
        ),
    ]
