# Generated by Django 4.2.2 on 2023-07-18 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0015_rename_rele_englishwords_rule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='englishwords',
            name='rules',
        ),
    ]
