# Generated by Django 4.2.2 on 2023-07-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0017_englishwords_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='englishwords',
            name='rule',
            field=models.ManyToManyField(null=True, to='Blog.rulesofenglish'),
        ),
    ]
